C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="DA_CIPB" --energy_price_inst="Energy_prices_DA_CIPB" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=.8332999945 --output_efficiency_inst=1 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="DA_CIPV" --energy_price_inst="Energy_prices_DA_CIPV" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=0.912852669 --output_efficiency_inst=0.912852669 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="DA_CISC" --energy_price_inst="Energy_prices_DA_CISC" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=0.912852669 --output_efficiency_inst=0.912852669 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="DA_CISD" --energy_price_inst="Energy_prices_DA_CISD" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=.8332999945 --output_efficiency_inst=1 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="HA_CIPB" --energy_price_inst="Energy_prices_HA_CIPB" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=.8332999945 --output_efficiency_inst=1 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="HA_CIPV" --energy_price_inst="Energy_prices_HA_CIPV" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=0.912852669 --output_efficiency_inst=0.912852669 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="HA_CISC" --energy_price_inst="Energy_prices_HA_CISC" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=0.912852669 --output_efficiency_inst=0.912852669 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="HA_CISD" --energy_price_inst="Energy_prices_HA_CISD" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=.8332999945 --output_efficiency_inst=1 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="RT_CIPB" --energy_price_inst="Energy_prices_RT_CIPB" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=.8332999945 --output_efficiency_inst=1 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="RT_CIPV" --energy_price_inst="Energy_prices_RT_CIPV" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=0.912852669 --output_efficiency_inst=0.912852669 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="RT_CISC" --energy_price_inst="Energy_prices_RT_CISC" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=0.912852669 --output_efficiency_inst=0.912852669 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"

"C:\GAMS\win64\24.8\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\win64\24.8\gamslice.txt --file_name_instance="RT_CISD" --energy_price_inst="Energy_prices_RT_CISD" --AS_price_inst="Ancillary_services_hourly" --input_cap_instance=1000 --output_cap_instance=1000 --input_LSL_instance=0 --output_LSL_instance=0 --ramp_penalty_instance=0 --input_efficiency_inst=.8332999945 --output_efficiency_inst=1 --in_heat_rate_instance=0 --out_heat_rate_instance=0 --storage_cap_instance=6 --op_length_instance=8784 --op_period_instance=8784 --lookahead_instance=0 --int_length_instance=1 --lookahead_instance=0 --energy_only_instance=1 --Renewable_MW_instance=0 --elec_rate_instance="BLANK_hourly" --add_param_instance="additional_parameters_hourly" --ren_prof_instance="renewable_profiles_none_hourly" --Load_prof_instance="basic_building_0_hourly" --outdir="Output\Redispatch_hourly" --indir="data_files\Redispatch_hourly\TXT_files"



